module Domainic
  module Attributer
    # A singleton object representing an undefined value
    #
    # This object is used throughout {Domainic::Attributer} to represent values that
    # are explicitly undefined, as opposed to nil which represents the absence of
    # a value. It is immutable and implements custom string representations for
    # debugging purposes
    #
    # @api private
    # @!visibility private
    # @author {https://aaronmallen.me Aaron Allen}
    # @since 0.1.0
    Undefined: Object
  end
end
